ARG AWG_TOOLS_VERSION=v3.1.20260812

FROM --platform=$BUILDPLATFORM golang:1.26.3-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

RUN apk update && apk add --no-cache make

WORKDIR /src

COPY go* .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} make NAME=main build

FROM alpine:latest AS awg-builder

ARG AWG_TOOLS_VERSION
RUN apk add --no-cache git build-base
RUN git clone --depth 1 --branch ${AWG_TOOLS_VERSION} https://github.com/amnezia-vpn/amneziawg-tools.git /src/amneziawg-tools && make -C /src/amneziawg-tools/src

FROM alpine:latest

LABEL org.opencontainers.image.source="https://github.com/PasarGuard/node"

RUN apk update && apk add --no-cache wireguard-tools nftables iproute2
COPY --from=awg-builder /src/amneziawg-tools/src/awg /usr/bin/awg

WORKDIR /app
COPY --from=builder /src /app

ENTRYPOINT ["./main"]
